### ISSUE TITLE
The code can't download

### ISSUE THREAD

**Issue by gll-sketch** [Flowerfan/SPamCo#1]
This code download shows that the folder is damaged, and not all the contents have been downloaded. Is it because the document is too large?

**Comment by Flowerfan** [comment]
Hi, I just downloaded the zip file which is about 14m.https://github.com/Flowerfan/SPamCo/archive/master.zip  You can try it again or check your internet.

**Comment by gll-sketch** [comment]
> Hi, I just downloaded the zip file which is about 14m.https://github.com/Flowerfan/SPamCo/archive/master.zip You can try it again or check your internet.

Thank you very much ! I have downloaded it successfully！
